# Generated by Django 5.2.4 on 2025-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='distributed',
            field=models.BooleanField(default=False),
        ),
    ]
