# Generated by Django 5.2.4 on 2025-07-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_investment_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(default='MON', max_length=20),
        ),
    ]
