# Generated by Django 5.2.4 on 2025-08-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_investment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='distributed_per',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='property',
            name='returns_pool',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
    ]
